// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://dataspacebuilder.github.io',
  base: '/learning-paths',
  redirects: {
    '/system-integration': '/learning-paths/application/',
    '/system-integration/publishing-data': '/learning-paths/application/04-publishing-data/',
    '/system-integration/consuming-data': '/learning-paths/application/05-consuming-data/',
    '/system-integration/management-api': '/learning-paths/application/06-management-api/',
    '/system-integration/identity-hub': '/learning-paths/application/07-identity-hub/',
    '/system-integration/data-plane-architecture': '/learning-paths/application/09-data-plane-architecture/',
    '/system-integration/deploying-a-data-plane': '/learning-paths/application/10-build-or-deploy-data-plane/',
  },
  integrations: [
    starlight({
      title: 'Learn Dataspaces',
      description: 'Guided paths for understanding, operating, and building sovereign data sharing systems.',
      sidebar: [
        {
          label: 'A Dataspace Use Case',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'use-case' },
            { label: 'The Problem', slug: 'use-case/01-the-problem' },
            { label: 'The Companies', slug: 'use-case/02-the-companies' },
            { label: 'How a Dataspace Works', slug: 'use-case/03-how-a-dataspace-works' },
            { label: 'Provider Publishes Data', slug: 'use-case/04-provider-publishes-data' },
            { label: 'Consumer Discovers and Negotiates', slug: 'use-case/05-consumer-discovers-and-negotiates' },
            { label: 'Consumer Becomes Provider', slug: 'use-case/06-consumer-becomes-provider' },
            { label: 'Trust Enters the Picture', slug: 'use-case/07-trust-enters-the-picture' },
            { label: 'Multiple Consumers and Use Cases', slug: 'use-case/08-multiple-consumers-and-use-cases' },
            { label: 'Updates and Notifications', slug: 'use-case/09-updates-and-notifications' },
            { label: 'Trust Changes', slug: 'use-case/10-trust-changes' },
            { label: 'What We Built', slug: 'use-case/11-what-we-built' },
            { label: 'Is a Dataspace Right for You?', slug: 'use-case/12-is-a-dataspace-right-for-you' },
          ],
        },
        {
          label: 'Set Up a Dataspace Platform',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'platform-setup' },
            { label: 'Platform Operating Models', slug: 'platform-setup/01-platform-operating-models' },
            { label: 'Component Map', slug: 'platform-setup/02-component-map' },
            { label: 'What Eclipse Provides vs. What You Build', slug: 'platform-setup/03-responsibility-split' },
            { label: 'Infrastructure Prerequisites', slug: 'platform-setup/04-prerequisites' },
            { label: 'Deploy EDC Services', slug: 'platform-setup/05-edc-services' },
            { label: 'Deploy Connector Fabric Manager', slug: 'platform-setup/06-connector-fabric-manager' },
            { label: 'Deploy Activity Agents', slug: 'platform-setup/07-activity-agents' },
            { label: 'Identity Provider Setup', slug: 'platform-setup/08-identity-provider-setup' },
            { label: 'Dataspace Profiles and Cells', slug: 'platform-setup/09-dataspace-profiles-and-cells' },
            { label: 'Provision Participants', slug: 'platform-setup/10-provisioning-participants' },
            { label: 'Customer Handoff', slug: 'platform-setup/11-customer-handoff' },
            { label: 'Self-Hosted Connector Track', slug: 'platform-setup/12-self-hosted-connector-track' },
            { label: 'Add Portal and Observability', slug: 'platform-setup/13-portal-and-observability' },
            { label: 'Add Data Plane Capabilities', slug: 'platform-setup/14-data-plane-capabilities' },
            { label: 'Optional Platform Services', slug: 'platform-setup/15-optional-platform-services' },
            { label: 'From Baseline to Offering', slug: 'platform-setup/16-baseline-to-offering' },
          ],
        },
        {
          label: 'Build a Dataspace Application',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'application' },
            { label: 'What You Are Building', slug: 'application/01-what-you-are-building' },
            { label: 'What You Receive from the Platform', slug: 'application/02-platform-handoff' },
            { label: 'Application Architecture', slug: 'application/03-application-architecture' },
            { label: 'Publishing Data', slug: 'application/04-publishing-data' },
            { label: 'Consuming Data', slug: 'application/05-consuming-data' },
            { label: 'Working with the Management API', slug: 'application/06-management-api' },
            { label: 'Working with Identity Hub', slug: 'application/07-identity-hub' },
            { label: 'Policy Design for Applications', slug: 'application/08-policy-design' },
            { label: 'Data Plane Architecture', slug: 'application/09-data-plane-architecture' },
            { label: 'Build or Deploy a Data Plane', slug: 'application/10-build-or-deploy-data-plane' },
            { label: 'Application as Data Plane', slug: 'application/11-application-as-data-plane' },
            { label: 'Deployment and Operations', slug: 'application/12-deployment-and-operations' },
            { label: 'End-to-End Example', slug: 'application/13-end-to-end-example' },
          ],
        },
        {
          label: 'Design Trust, Credentials, and Dataspace Profiles',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'trust-and-profiles' },
            { label: 'Why Trust Matters', slug: 'trust-and-profiles/01-why-trust-matters' },
            { label: 'Roles in the Trust Model', slug: 'trust-and-profiles/02-roles-in-the-trust-model' },
            { label: 'Define the Dataspace Profile', slug: 'trust-and-profiles/03-dataspace-profiles' },
            { label: 'Design the Membership Credential', slug: 'trust-and-profiles/04-credential-types-and-schemas' },
            { label: 'Onboard Members and Issue the First Credential', slug: 'trust-and-profiles/05-legal-vs-technical-onboarding' },
            { label: 'Manage Credential Lifecycle', slug: 'trust-and-profiles/07-credential-lifecycle' },
            { label: 'Turn Rules into Policy Patterns', slug: 'trust-and-profiles/08-policies-and-credentials' },
            { label: 'From Pilot to Scale', slug: 'trust-and-profiles/09-from-pilot-to-scale' },
          ],
        },
      ],
    }),
  ],
});
