// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://dataspacebuilder.github.io',
  base: '/learning-paths',
  redirects: {
    '/system-integration': '/learning-paths/application/',
    '/system-integration/publishing-data': '/learning-paths/application/publishing-data/',
    '/system-integration/consuming-data': '/learning-paths/application/consuming-data/',
    '/system-integration/management-api': '/learning-paths/application/management-api/',
    '/system-integration/identity-hub': '/learning-paths/application/identity-hub/',
    '/system-integration/data-plane-architecture': '/learning-paths/application/data-plane-architecture/',
    '/system-integration/deploying-a-data-plane': '/learning-paths/application/build-or-deploy-data-plane/',
  },
  integrations: [
    starlight({
      title: 'Learn Dataspaces',
      description: 'Guided paths for understanding, operating, and building sovereign data sharing systems.',
      sidebar: [
        {
          label: 'A Dataspace Use Case',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'use-case' },
            { label: 'The Problem', slug: 'use-case/the-problem' },
            { label: 'The Companies', slug: 'use-case/the-companies' },
            { label: 'How a Dataspace Works', slug: 'use-case/how-a-dataspace-works' },
            { label: 'Provider Publishes Data', slug: 'use-case/provider-publishes-data' },
            { label: 'Consumer Discovers and Negotiates', slug: 'use-case/consumer-discovers-and-negotiates' },
            { label: 'Consumer Becomes Provider', slug: 'use-case/consumer-becomes-provider' },
            { label: 'Trust Enters the Picture', slug: 'use-case/trust-enters-the-picture' },
            { label: 'Multiple Consumers and Use Cases', slug: 'use-case/multiple-consumers-and-use-cases' },
            { label: 'Updates and Notifications', slug: 'use-case/updates-and-notifications' },
            { label: 'Trust Changes', slug: 'use-case/trust-changes' },
            { label: 'What We Built', slug: 'use-case/what-we-built' },
            { label: 'Is a Dataspace Right for You?', slug: 'use-case/is-a-dataspace-right-for-you' },
          ],
        },
        {
          label: 'Set Up a Dataspace Platform',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'platform-setup' },
            { label: 'Platform Operating Models', slug: 'platform-setup/platform-operating-models' },
            { label: 'Component Map', slug: 'platform-setup/component-map' },
            { label: 'What Eclipse Provides vs. What You Build', slug: 'platform-setup/responsibility-split' },
            { label: 'Infrastructure Prerequisites', slug: 'platform-setup/prerequisites' },
            { label: 'Deploy EDC Services', slug: 'platform-setup/edc-services' },
            { label: 'Deploy Connector Fabric Manager', slug: 'platform-setup/connector-fabric-manager' },
            { label: 'Deploy Activity Agents', slug: 'platform-setup/activity-agents' },
            { label: 'Identity Provider Setup', slug: 'platform-setup/identity-provider-setup' },
            { label: 'Dataspace Profiles and Cells', slug: 'platform-setup/dataspace-profiles-and-cells' },
            { label: 'Provision Participants', slug: 'platform-setup/provisioning-participants' },
            { label: 'Customer Handoff', slug: 'platform-setup/customer-handoff' },
            { label: 'Self-Hosted Connector Track', slug: 'platform-setup/self-hosted-connector-track' },
            { label: 'Add Portal and Observability', slug: 'platform-setup/portal-and-observability' },
            { label: 'Add Data Plane Capabilities', slug: 'platform-setup/data-plane-capabilities' },
            { label: 'Optional Platform Services', slug: 'platform-setup/optional-platform-services' },
            { label: 'From Baseline to Offering', slug: 'platform-setup/baseline-to-offering' },
          ],
        },
        {
          label: 'Build a Dataspace Application',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'application' },
            { label: 'What You Are Building', slug: 'application/what-you-are-building' },
            { label: 'What You Receive from the Platform', slug: 'application/platform-handoff' },
            { label: 'Application Architecture', slug: 'application/application-architecture' },
            { label: 'Publishing Data', slug: 'application/publishing-data' },
            { label: 'Consuming Data', slug: 'application/consuming-data' },
            { label: 'Working with the Management API', slug: 'application/management-api' },
            { label: 'Working with Identity Hub', slug: 'application/identity-hub' },
            { label: 'Policy Design for Applications', slug: 'application/policy-design' },
            { label: 'Data Plane Architecture', slug: 'application/data-plane-architecture' },
            { label: 'Build or Deploy a Data Plane', slug: 'application/build-or-deploy-data-plane' },
            { label: 'Application as Data Plane', slug: 'application/application-as-data-plane' },
            { label: 'Deployment and Operations', slug: 'application/deployment-and-operations' },
            { label: 'End-to-End Example', slug: 'application/end-to-end-example' },
          ],
        },
        {
          label: 'Design Trust, Credentials, and Dataspace Profiles',
          collapsed: true,
          items: [
            { label: 'Overview', slug: 'trust-and-profiles' },
            { label: 'Why Trust Matters', slug: 'trust-and-profiles/why-trust-matters' },
            { label: 'Roles in the Trust Model', slug: 'trust-and-profiles/roles-in-the-trust-model' },
            { label: 'Dataspace Profiles', slug: 'trust-and-profiles/dataspace-profiles' },
            { label: 'Credential Types and Schemas', slug: 'trust-and-profiles/credential-types-and-schemas' },
            { label: 'Legal vs. Technical Onboarding', slug: 'trust-and-profiles/legal-vs-technical-onboarding' },
            { label: 'The Role of the Issuer Service', slug: 'trust-and-profiles/issuer-service' },
            { label: 'Credential Lifecycle', slug: 'trust-and-profiles/credential-lifecycle' },
            { label: 'Policies and Credentials', slug: 'trust-and-profiles/policies-and-credentials' },
            { label: 'Multiple Issuers and Trust Lists', slug: 'trust-and-profiles/multiple-issuers-and-trust-lists' },
            { label: 'Multi-Dataspace Configuration', slug: 'trust-and-profiles/multi-dataspace-configuration' },
            { label: 'From Pilot to Scale', slug: 'trust-and-profiles/from-pilot-to-scale' },
          ],
        },
      ],
    }),
  ],
});
